/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tuan12;
import java.util.Vector;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
public class QUANLY3 extends javax.swing.JFrame {
    public static String dbURL="jdbc:sqlserver://127.0.0.1;databaseName=QLSP;user=sa;password=123";
    public static Connection getConnection(){
        Connection conn =null;
        try{
            conn = DriverManager.getConnection(dbURL);
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        return conn;
    }
    public QUANLY3() {
        initComponents();
        loadttsp();
        loadlsp();
        addlsp();
        addhang();
        loadtb3();
        addma();
        addnpp();
        loadtb4();
        addpn();
        addsp();
        loadtb5();
    }   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        masp = new javax.swing.JTextField();
        tensp = new javax.swing.JTextField();
        loaisp = new javax.swing.JComboBox<>();
        hangsx = new javax.swing.JComboBox<>();
        gianhap = new javax.swing.JTextField();
        giaban = new javax.swing.JTextField();
        tonkho = new javax.swing.JTextField();
        ghichu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        maloaisp = new javax.swing.JTextField();
        tenloaisp = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb5 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        maphieunhap = new javax.swing.JTextField();
        tongtien = new javax.swing.JTextField();
        ngaynhap = new javax.swing.JTextField();
        ghichu1 = new javax.swing.JTextField();
        manhanvien = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb3 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ctpn = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        msp = new javax.swing.JComboBox<>();
        sl1 = new javax.swing.JTextField();
        gc2 = new javax.swing.JTextField();
        mpn = new javax.swing.JComboBox<>();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb4 = new javax.swing.JTable();
        manhaphanphoi = new javax.swing.JComboBox<>();
        tt1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã sản phẩm");

        jLabel2.setText("Tên sản phẩm");

        jLabel3.setText("Mã loại sẩn phẩm");

        jLabel4.setText("Hãng sản xuất");

        jLabel5.setText("Giá nhập");

        jLabel6.setText("Giá bán");

        jLabel7.setText("Tồn kho");

        jLabel8.setText("Ghi chú");

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Tìm kiếm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("BẢNG THÔNG TIN SẢN PHẨM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(43, 43, 43)
                                        .addComponent(tensp))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(45, 45, 45)
                                        .addComponent(masp, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hangsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(loaisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(7, 7, 7)))
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gianhap, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(giaban, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tonkho, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(33, 33, 33)
                                        .addComponent(ghichu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(masp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButton1))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton2)
                    .addComponent(giaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(loaisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tonkho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButton3))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hangsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ghichu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jLabel8))
                .addGap(32, 32, 32)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông tin sản phẩm", jPanel1);

        jLabel9.setText("Mã loại sản phẩm");

        jLabel10.setText("Tên loại sản phẩm");

        jButton5.setText("Thêm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Sửa");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Xóa");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Tìm kiếm");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb2);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("BẢNG LOẠI SẢN PHẨM");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("BẢNG THÔNG TIN SẢN PHẨM");

        tb5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb5MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tb5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(maloaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton5)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tenloaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addComponent(jButton7)))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel24))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel27))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(maloaisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton7)
                            .addComponent(tenloaisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Loại sản phẩm", jPanel2);

        jLabel11.setText("Mã phiếu nhập");

        jLabel12.setText("Mã nhân viên");

        jLabel13.setText("Mã nhà phân phối");

        jLabel14.setText("Tổng tiền");

        jLabel15.setText("Ngày nhập");

        jLabel16.setText("Ghi chú");

        jButton9.setText("Thêm");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Sửa");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Xóa");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Tìm kiếm");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        tb3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb3);

        jLabel17.setText("Mã chi tiết PN");

        jLabel18.setText("Mã phiếu nhập");

        jLabel19.setText("Mã sản phẩm");

        jLabel20.setText("Số lượng");

        jLabel21.setText("Tổng tiền");

        jLabel22.setText("Ghi chú");

        jButton13.setText("Thêm");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Sửa");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Xóa");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Tìm kiếm");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        tb4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tb4);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("BẢNG PHIẾU NHẬP");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("CHI TIẾT PHIẾU NHẬP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(manhaphanphoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(manhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(29, 29, 29)
                                    .addComponent(maphieunhap, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(23, 23, 23))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(14, 14, 14)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ngaynhap)
                                .addComponent(tongtien)
                                .addComponent(ghichu1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addComponent(jLabel25)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(msp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mpn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ctpn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel17))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(sl1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(gc2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addGap(18, 18, 18)
                                    .addComponent(tt1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jButton13)
                            .addGap(30, 30, 30)
                            .addComponent(jButton14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton15)
                            .addGap(32, 32, 32)
                            .addComponent(jButton16))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel26)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel14))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(maphieunhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(manhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(manhaphanphoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ngaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ghichu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(75, 75, 75)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(gc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(ctpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(mpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(tt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(msp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel25)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton13)
                        .addComponent(jButton14)
                        .addComponent(jButton15)
                        .addComponent(jButton16))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton12)
                        .addComponent(jButton9)
                        .addComponent(jButton10)
                        .addComponent(jButton11)))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Phiếu nhập và chi tiết phiếu nhập", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try{
           Connection conn = getConnection();
           Statement st = conn.createStatement();
           String sql ="INSERT INTO LOAISP VALUES('"+maloaisp.getText()+"','"+tenloaisp.getText()+"')";
           int a = st.executeUpdate(sql);
       }catch(SQLException ex){
           ex.printStackTrace();
       }
       loadlsp();
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
               try{
           Connection conn = getConnection();
           Statement st = conn.createStatement();
           String sql ="UPDATE LOAISP SET tenloaisanpham='"+tenloaisp.getText()+"' WHERE maloaisanpham='"+maloaisp.getText()+"'";
           int a = st.executeUpdate(sql);
       }catch(SQLException ex){
           ex.printStackTrace();
       }
               loadlsp();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                       try{
           Connection conn = getConnection();
           Statement st = conn.createStatement();
           String sql ="DELETE FROM LOAISP WHERE maloaisanpham='"+maloaisp.getText()+"'";
           int a = st.executeUpdate(sql);
       }catch(SQLException ex){
           ex.printStackTrace();
       }
                       loadlsp();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    DefaultTableModel tb = new DefaultTableModel();
   tb.addColumn("Mã loại sản phẩm");
   tb.addColumn("Tên loại sản phẩm");

   try{
       Connection conn = getConnection();
       Statement st = conn.createStatement();
       ResultSet rs = st.executeQuery("SELECT * FROM LOAISP WHERE maloaisanpham='"+maloaisp.getText()+"'");
       while(rs.next()){
           Vector vt = new Vector();
           vt.add(rs.getString("maloaisanpham"));
           vt.add(rs.getString("tenloaisanpham"));
           tb.addRow(vt);
       }
       tb2.setModel(tb);
       
   }catch(SQLException ex){
       ex.printStackTrace();
   }      
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb2MouseClicked
      int row = tb2.getSelectedRow();
      maloaisp.setText(tb2.getValueAt(row, 0).toString());
      tenloaisp.setText(tb2.getValueAt(row, 1).toString());
      loadtb5();
    }//GEN-LAST:event_tb2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  try{
           Connection conn = getConnection();
           Statement st = conn.createStatement();
           String sql ="INSERT INTO SANPHAM VALUES('"+masp.getText()+"','"+tensp.getText()+"','"+loaisp.getSelectedItem()+"','"+hangsx.getSelectedItem()+"','"+gianhap.getText()+"','"+giaban.getText()+"','"+tonkho.getText()+"','"+ghichu.getText()+"')";
           int a = st.executeUpdate(sql);
       }catch(SQLException ex){
           ex.printStackTrace();
       }
       loadttsp();       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try{
           Connection conn = getConnection();
           Statement st = conn.createStatement();
           String sql = "UPDATE SANPHAM SET tensanpham='"+tensp.getText()+"', maloaisanpham='"+loaisp.getSelectedItem()+"', hangsanxuat='"+hangsx.getSelectedItem()+"', gianhap='"+gianhap.getText()+"',giaban='"+giaban.getText()+"',tonkho='"+tonkho.getText()+"',ghichu='"+ghichu.getText()+"' WHERE masanpham='"+masp.getText()+"'";
           int a = st.executeUpdate(sql);
       }catch(SQLException ex){
           ex.printStackTrace();
       }
       loadttsp();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
              try{
           Connection conn = getConnection();
           Statement st = conn.createStatement();
           String sql ="DELETE FROM SANPHAM WHERE masanpham='"+masp.getText()+"'";
           int a = st.executeUpdate(sql);
       }catch(SQLException ex){
           ex.printStackTrace();
       }
       loadttsp();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   DefaultTableModel tb = new DefaultTableModel();
   tb.addColumn("Mã sản phẩm");
   tb.addColumn("Tên sản phẩm");
   tb.addColumn("Mã loại sản phẩm");
   tb.addColumn("Hãng sản xuất");
   tb.addColumn("Giá nhập");
   tb.addColumn("Giá bán");
   tb.addColumn("Tồn kho");
   tb.addColumn("Ghi chú");
   try{
       Connection conn = getConnection();
       Statement st = conn.createStatement();
       ResultSet rs = st.executeQuery("SELECT * FROM SANPHAM WHERE masanpham='"+masp.getText()+"' OR tensanpham='"+tensp.getText()+"' OR maloaisanpham='"+loaisp.getSelectedItem()+"'");
       while(rs.next()){
           Vector vt = new Vector();
           vt.add(rs.getString("masanpham"));
           vt.add(rs.getString("tensanpham"));
           vt.add(rs.getString("maloaisanpham"));
           vt.add(rs.getString("hangsanxuat"));
           vt.add(rs.getString("gianhap"));
           vt.add(rs.getString("giaban"));
           vt.add(rs.getString("tonkho"));
           vt.add(rs.getString("ghichu"));
           tb.addRow(vt);
       }
       tb1.setModel(tb);
       
   }catch(SQLException ex){
       ex.printStackTrace();
   }       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
      int row = tb1.getSelectedRow();
      masp.setText(tb1.getValueAt(row, 0).toString());
      tensp.setText(tb1.getValueAt(row, 1).toString());
      loaisp.setSelectedItem(tb1.getValueAt(row, 2).toString());
      hangsx.setSelectedItem(tb1.getValueAt(row, 3).toString());
      giaban.setText(tb1.getValueAt(row, 4).toString());
      gianhap.setText(tb1.getValueAt(row, 5).toString());
      tonkho.setText(tb1.getValueAt(row, 6).toString());
      ghichu.setText(tb1.getValueAt(row, 7).toString());
    }//GEN-LAST:event_tb1MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try{
           Connection conn = getConnection();
           Statement st = conn.createStatement();
           String sql ="INSERT INTO PHIEUNHAP VALUES('"+maphieunhap.getText()+"','"+manhanvien.getSelectedItem()+"','"+manhaphanphoi.getSelectedItem()+"','"+tongtien.getText()+"','"+ngaynhap.getText()+"','"+ghichu1.getText()+"')";
           int a = st.executeUpdate(sql);
       }catch(SQLException ex){
           ex.printStackTrace();
       }
       loadtb3(); 
       
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
                try{
           Connection conn = getConnection();
           Statement st = conn.createStatement();
           String sql ="UPDATE PHIEUNHAP SET manhanvien='"+manhanvien.getSelectedItem()+"',manhaphanphoi='"+manhaphanphoi.getSelectedItem()+"',tongtien='"+tongtien.getText()+"',ngaynhap='"+ngaynhap.getText()+"',ghichu='"+ghichu1.getText()+"'WHERE maphieunhap='"+maphieunhap.getText()+"'";
           int a = st.executeUpdate(sql);
       }catch(SQLException ex){
           ex.printStackTrace();
       }
       loadtb3(); 
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
                     try{
           Connection conn = getConnection();
           Statement st = conn.createStatement();
           String sql ="DELETE FROM PHIEUNHAP WHERE maphieunhap='"+maphieunhap.getText()+"'";
           int a = st.executeUpdate(sql);
       }catch(SQLException ex){
           ex.printStackTrace();
       }
       loadtb3(); 
    }//GEN-LAST:event_jButton11ActionPerformed

    private void tb3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb3MouseClicked
      int row = tb3.getSelectedRow();
      maphieunhap.setText(tb3.getValueAt(row, 0).toString());
      manhanvien.setSelectedItem(tb3.getValueAt(row, 1).toString());
      manhaphanphoi.setSelectedItem(tb3.getValueAt(row, 2).toString());
      tongtien.setText(tb3.getValueAt(row, 4).toString());
      ngaynhap.setText(tb3.getValueAt(row, 5).toString());
      ghichu1.setText(tb3.getValueAt(row, 6).toString());
      mpn.setSelectedItem(tb3.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tb3MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
   DefaultTableModel tb = new DefaultTableModel();
   tb.addColumn("Mã phiếu nhập");
   tb.addColumn("Mã nhân viên");
   tb.addColumn("Mã nhà phân phối");
   tb.addColumn("Tên nhà phân phối");
   tb.addColumn("Tổng tiền");
   tb.addColumn("Ngày nhập");
   tb.addColumn("Ghi chú");
   try{
       Connection conn = getConnection();
       Statement st = conn.createStatement();
       ResultSet rs = st.executeQuery("SELECT * FROM PHIEUNHAP INNER JOIN NHAPP ON PHIEUNHAP.manhaphanphoi = NHAPP.manhaphanphoi WHERE maphieunhap='"+maphieunhap.getText()+"'");
       while(rs.next()){
           Vector vt = new Vector();
           vt.add(rs.getString("maphieunhap"));
           vt.add(rs.getString("manhanvien"));
           vt.add(rs.getString("manhaphanphoi"));
           vt.add(rs.getString("tennhaphanphoi"));
           vt.add(rs.getString("tongtien"));
           vt.add(rs.getString("ngaynhap"));
           vt.add(rs.getString("ghichu"));
           tb.addRow(vt);
       }
       tb3.setModel(tb);
       
   }catch(SQLException ex){
       ex.printStackTrace();
   }     
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
                try{
           Connection conn = getConnection();
           Statement st = conn.createStatement();
           String sql ="INSERT INTO CTPHIEUNHAP VALUES('"+ctpn.getText()+"','"+mpn.getSelectedItem()+"','"+msp.getSelectedItem()+"','"+sl1.getText()+"','"+tt1.getText()+"','"+gc2.getText()+"')";
           int a = st.executeUpdate(sql);
       }catch(SQLException ex){
           ex.printStackTrace();
       }
       loadtb4(); 
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
                       try{
           Connection conn = getConnection();
           Statement st = conn.createStatement();
           String sql ="UPDATE CTPHIEUNHAP SET maphieunhap='"+mpn.getSelectedItem()+"', masanpham='"+msp.getSelectedItem()+"',soluong='"+sl1.getText()+"',tongtien='"+tt1.getText()+"',ghichu='"+gc2.getText()+"' WHERE mactpn='"+ctpn.getText()+"'";
           int a = st.executeUpdate(sql);
       }catch(SQLException ex){
           ex.printStackTrace();
       }
       loadtb4();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
                            try{
           Connection conn = getConnection();
           Statement st = conn.createStatement();
           String sql ="DELETE FROM CTPHIEUNHAP WHERE mactpn='"+ctpn.getText()+"'";
           int a = st.executeUpdate(sql);
       }catch(SQLException ex){
           ex.printStackTrace();
       }
       loadtb4();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
   DefaultTableModel tb = new DefaultTableModel();
   tb.addColumn("Mã chi tiết pn");
   tb.addColumn("Mã phiếu nhập");
   tb.addColumn("Mã sản phẩm");
   tb.addColumn("Số lượng");
   tb.addColumn("Tổng tiền");
   tb.addColumn("Ghi chú");
   try{
       Connection conn = getConnection();
       Statement st = conn.createStatement();
       ResultSet rs = st.executeQuery("SELECT * FROM CTPHIEUNHAP WHERE mactpn='"+ctpn.getText()+"'");
       while(rs.next()){
           Vector vt = new Vector();
           vt.add(rs.getString("mactpn"));
           vt.add(rs.getString("maphieunhap"));
           vt.add(rs.getString("masanpham"));
           vt.add(rs.getString("soluong"));
           vt.add(rs.getString("tongtien"));
           vt.add(rs.getString("ghichu"));
           tb.addRow(vt);
       }
       tb4.setModel(tb);
       
   }catch(SQLException ex){
       ex.printStackTrace();
   
    }      
    }//GEN-LAST:event_jButton16ActionPerformed

    private void tb4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb4MouseClicked
      int row = tb4.getSelectedRow();
      ctpn.setText(tb4.getValueAt(row, 0).toString());
      mpn.setSelectedItem(tb4.getValueAt(row, 1).toString());
      msp.setSelectedItem(tb4.getValueAt(row, 2).toString());
      sl1.setText(tb4.getValueAt(row, 3).toString());
      tt1.setText(tb4.getValueAt(row, 4).toString());
      gc2.setText(tb4.getValueAt(row, 5).toString());            
    }//GEN-LAST:event_tb4MouseClicked

    private void tb5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb5MouseClicked

    }//GEN-LAST:event_tb5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QUANLY3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QUANLY3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QUANLY3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QUANLY3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QUANLY3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ctpn;
    private javax.swing.JTextField gc2;
    private javax.swing.JTextField ghichu;
    private javax.swing.JTextField ghichu1;
    private javax.swing.JTextField giaban;
    private javax.swing.JTextField gianhap;
    private javax.swing.JComboBox<String> hangsx;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> loaisp;
    private javax.swing.JTextField maloaisp;
    private javax.swing.JComboBox<String> manhanvien;
    private javax.swing.JComboBox<String> manhaphanphoi;
    private javax.swing.JTextField maphieunhap;
    private javax.swing.JTextField masp;
    private javax.swing.JComboBox<String> mpn;
    private javax.swing.JComboBox<String> msp;
    private javax.swing.JTextField ngaynhap;
    private javax.swing.JTextField sl1;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    private javax.swing.JTable tb3;
    private javax.swing.JTable tb4;
    private javax.swing.JTable tb5;
    private javax.swing.JTextField tenloaisp;
    private javax.swing.JTextField tensp;
    private javax.swing.JTextField tongtien;
    private javax.swing.JTextField tonkho;
    private javax.swing.JTextField tt1;
    // End of variables declaration//GEN-END:variables

    private void loadttsp() {
   DefaultTableModel tb = new DefaultTableModel();
   tb.addColumn("Mã sản phẩm");
   tb.addColumn("Tên sản phẩm");
   tb.addColumn("Mã loại sản phẩm");
   tb.addColumn("Hãng sản xuất");
   tb.addColumn("Giá nhập");
   tb.addColumn("Giá bán");
   tb.addColumn("Tồn kho");
   tb.addColumn("Ghi chú");
   try{
       Connection conn = getConnection();
       Statement st = conn.createStatement();
       ResultSet rs = st.executeQuery("SELECT * FROM SANPHAM");
       while(rs.next()){
           Vector vt = new Vector();
           vt.add(rs.getString("masanpham"));
           vt.add(rs.getString("tensanpham"));
           vt.add(rs.getString("maloaisanpham"));
           vt.add(rs.getString("hangsanxuat"));
           vt.add(rs.getString("gianhap"));
           vt.add(rs.getString("giaban"));
           vt.add(rs.getString("tonkho"));
           vt.add(rs.getString("ghichu"));
           tb.addRow(vt);
       }
       tb1.setModel(tb);
       
   }catch(SQLException ex){
       ex.printStackTrace();
   }
    }

    private void loadlsp() {
         DefaultTableModel tb = new DefaultTableModel();
   tb.addColumn("Mã loại sản phẩm");
   tb.addColumn("Tên loại sản phẩm");

   try{
       Connection conn = getConnection();
       Statement st = conn.createStatement();
       ResultSet rs = st.executeQuery("SELECT * FROM LOAISP");
       while(rs.next()){
           Vector vt = new Vector();
           vt.add(rs.getString("maloaisanpham"));
           vt.add(rs.getString("tenloaisanpham"));
           tb.addRow(vt);
       }
       tb2.setModel(tb);
       
   }catch(SQLException ex){
       ex.printStackTrace();
   }
    }

    private void addlsp() {
     try{
       Connection conn = getConnection();
       Statement st = conn.createStatement();
        loaisp.addItem("");
       ResultSet rs = st.executeQuery("SELECT * FROM LOAISP");
       while(rs.next()){
           loaisp.addItem(rs.getString("maloaisanpham"));
       }
       
   }catch(SQLException ex){
       ex.printStackTrace();
   }
    }

    private void addhang() {
          try{
       Connection conn = getConnection();
       Statement st = conn.createStatement();
       ResultSet rs = st.executeQuery("SELECT * FROM HANGSX");
       while(rs.next()){
           hangsx.addItem(rs.getString("tenhangsanxuat"));
       }
       
   }catch(SQLException ex){
       ex.printStackTrace();
   }
    }

    private void loadtb3() {
      DefaultTableModel tb = new DefaultTableModel();
   tb.addColumn("Mã phiếu nhập");
   tb.addColumn("Mã nhân viên");
   tb.addColumn("Mã nhà phân phối");
   tb.addColumn("Tên nhà phân phối");
   tb.addColumn("Tổng tiền");
   tb.addColumn("Ngày nhập");
   tb.addColumn("Ghi chú");
   try{
       Connection conn = getConnection();
       Statement st = conn.createStatement();
       ResultSet rs = st.executeQuery("SELECT * FROM PHIEUNHAP INNER JOIN NHAPP ON PHIEUNHAP.manhaphanphoi = NHAPP.manhaphanphoi");
       while(rs.next()){
           Vector vt = new Vector();
           vt.add(rs.getString("maphieunhap"));
           vt.add(rs.getString("manhanvien"));
           vt.add(rs.getString("manhaphanphoi"));
           vt.add(rs.getString("tennhaphanphoi"));
           vt.add(rs.getString("tongtien"));
           vt.add(rs.getString("ngaynhap"));
           vt.add(rs.getString("ghichu"));
           tb.addRow(vt);
       }
       tb3.setModel(tb);
       
   }catch(SQLException ex){
       ex.printStackTrace();
   }   
    }

    private void addma() {
              try{
       Connection conn = getConnection();
       Statement st = conn.createStatement();
       ResultSet rs = st.executeQuery("SELECT * FROM NHANVIEN");
       while(rs.next()){
           manhanvien.addItem(rs.getString("manhanvien"));
       }
       
   }catch(SQLException ex){
       ex.printStackTrace();
   }
    }

    private void addnpp() {
            try{
       Connection conn = getConnection();
       Statement st = conn.createStatement();
       ResultSet rs = st.executeQuery("SELECT * FROM NHAPP");
       while(rs.next()){
           manhaphanphoi.addItem(rs.getString("manhaphanphoi"));
       }
       
   }catch(SQLException ex){
       ex.printStackTrace();
   }
    }

    private void loadtb4() {
    DefaultTableModel tb = new DefaultTableModel();
   tb.addColumn("Mã chi tiết pn");
   tb.addColumn("Mã phiếu nhập");
   tb.addColumn("Mã sản phẩm");
   tb.addColumn("Số lượng");
   tb.addColumn("Tổng tiền");
   tb.addColumn("Ghi chú");
   try{
       Connection conn = getConnection();
       Statement st = conn.createStatement();
       ResultSet rs = st.executeQuery("SELECT * FROM CTPHIEUNHAP");
       while(rs.next()){
           Vector vt = new Vector();
           vt.add(rs.getString("mactpn"));
           vt.add(rs.getString("maphieunhap"));
           vt.add(rs.getString("masanpham"));
           vt.add(rs.getString("soluong"));
           vt.add(rs.getString("tongtien"));
           vt.add(rs.getString("ghichu"));
           tb.addRow(vt);
       }
       tb4.setModel(tb);
       
   }catch(SQLException ex){
       ex.printStackTrace();
   
    }
    }

    private void addpn() {
           try{
       Connection conn = getConnection();
       Statement st = conn.createStatement();
       ResultSet rs = st.executeQuery("SELECT * FROM PHIEUNHAP");
       while(rs.next()){
          mpn.addItem(rs.getString("maphieunhap"));
       }
       
   }catch(SQLException ex){
       ex.printStackTrace();
   }
    }

    private void addsp() {
            try{
       Connection conn = getConnection();
       Statement st = conn.createStatement();
       ResultSet rs = st.executeQuery("SELECT * FROM SANPHAM");
       while(rs.next()){
           msp.addItem(rs.getString("masanpham"));
       }
       
   }catch(SQLException ex){
       ex.printStackTrace();
   }
    }

    private void loadtb5() {
     DefaultTableModel tb = new DefaultTableModel();
   tb.addColumn("Mã sản phẩm");
   tb.addColumn("Tên sản phẩm");
   tb.addColumn("Mã loại sản phẩm");
   tb.addColumn("Hãng sản xuất");
   tb.addColumn("Giá nhập");
   tb.addColumn("Giá bán");
   tb.addColumn("Tồn kho");
   tb.addColumn("Ghi chú");
   try{
       Connection conn = getConnection();
       Statement st = conn.createStatement();
       ResultSet rs = st.executeQuery("SELECT * FROM SANPHAM WHERE maloaisanpham='"+maloaisp.getText()+"'");
       while(rs.next()){
           Vector vt = new Vector();
           vt.add(rs.getString("masanpham"));
           vt.add(rs.getString("tensanpham"));
           vt.add(rs.getString("maloaisanpham"));
           vt.add(rs.getString("hangsanxuat"));
           vt.add(rs.getString("gianhap"));
           vt.add(rs.getString("giaban"));
           vt.add(rs.getString("tonkho"));
           vt.add(rs.getString("ghichu"));
           tb.addRow(vt);
       }
       tb5.setModel(tb);
       
   }catch(SQLException ex){
       ex.printStackTrace();
   }       
    }
}
